# Dependencies
markdown:    kramdown
highlighter: rouge

# Permalinks
permalink:   pretty

# Setup
title:       London Genetics Network
tagline:     ''
description: ''
url:         https://github.com/LdnGeneNet/LondonGeneticsNetwork/
baseurl:     /
lastmod:    '15 November 2022'

author:
  name:      'London Genetics Network'
  url:       https://github.com/LdnGeneNet/LondonGeneticsNetwork/
  email:     londongeneticsnetwork@gmail.com
  twitter: LdnGeneNet

pagination:
  indexpage: 'blog'

# Plugins
plugins: ['jekyll-twitter-plugin']